Repository PhoenixFE/orum-market-front, pull requests merged in 2023-12, with the labels that each got.

#71 Fix: 샘플 데이터 수정 시 이미지 조회 오류 해결
  src/components/seller/ProductUpdate.tsx
Labels: 👾 Bug

#79 Feat: 상품 등록 후 알럿창 구현 및 경로 이동
  src/components/seller/ProductCreate.tsx
Labels: ✨ Feature

#111 Refactor: 변수명 변경 및 사이드바 폰트 두께 변경
  src/components/DashboardNavBar.tsx
  src/components/buyer/OrderListTable.tsx
Labels: 🛠️ Refactor
